# Generated by Django 4.2.5 on 2023-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Аватарка'),
        ),
    ]
