# Generated by Django 4.2.5 on 2023-09-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
