# Generated by Django 4.2.3 on 2023-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Сюда пишем заголовок товара', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Сюда пишем описание товара', max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Сюда пишем цену товара', max_digits=10, verbose_name='Цена')),
                ('auctions', models.BooleanField(default=False, help_text='Сюда пишем аукцион товара', verbose_name='Аукцион')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
