# Generated by Django 4.2.4 on 2023-08-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisement_contact_advertisement_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='email',
        ),
    ]
