# Generated by Django 4.2.4 on 2023-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_remove_advertisement_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='contact',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
