# Generated by Django 4.2.4 on 2023-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_alter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='contact',
            field=models.TextField(default='', max_length=20, verbose_name='Контакты'),
            preserve_default=False,
        ),
    ]
