# Generated by Django 4.2.4 on 2023-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_advertisement_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='Контакты'),
        ),
    ]
