# Generated by Django 4.2.4 on 2023-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0007_alter_advertisement_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Дополнительное Изображение'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Дополнительное Изображение'),
        ),
    ]
