# Generated by Django 4.2.4 on 2023-08-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0008_rename_image_advertisement_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favourites',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
