# Generated by Django 4.2.4 on 2023-08-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0010_alter_advertisement_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favourites',
        ),
    ]
