# Generated by Django 4.2.5 on 2023-09-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0012_advertisement_image_alter_advertisement_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='first_name',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='last_name',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='username',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Аватарка'),
        ),
    ]
