# Generated by Django 4.2.5 on 2023-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0014_remove_advertisement_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Дополнительное Изображение'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Дополнительное Изображение'),
        ),
    ]
